/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package epostest;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author Caitl
 */
public class EposMainPage extends javax.swing.JFrame {
//global manager variable
private boolean manager;
//global logged in employee
private Employee loggedInEmployee;
//global arraylist of employees for login
private ArrayList<Employee> employees;
// global quantity variable to select quantities
private int qtySelect;
// global orders arraylist to store orders
private ArrayList<Order> orders;
//global order total variable for display and reports
private double orderTotal;
// getting products
private ArrayList<Products> productList;


    
    
    /**
     * Creates new form EposMainPage
     */
    public EposMainPage(ArrayList<Employee> employeesIn, Employee empIn, boolean managerIn, ArrayList<Order> orderIn) {
        
        
        //bringing through employee details from login
        loggedInEmployee = empIn;
        //bringing through employee arraylist
        employees = employeesIn;
        //bringing through manager details
        manager = managerIn;
        //setting first quantity
        qtySelect = 1;   
        //setting order total as 0
        orderTotal = 0.0;
        initComponents();

        

       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblHello = new javax.swing.JLabel();
        lblDateTime = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        tbMain = new javax.swing.JTabbedPane();
        tbShop = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn0 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnOrange = new javax.swing.JButton();
        btnApple = new javax.swing.JButton();
        btnPotato = new javax.swing.JButton();
        btnCarrot = new javax.swing.JButton();
        btnMilk = new javax.swing.JButton();
        btnORange3 = new javax.swing.JButton();
        btnOnion = new javax.swing.JButton();
        btnBread = new javax.swing.JButton();
        btnEggs = new javax.swing.JButton();
        lblQty = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtOrder = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnCheckOut = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        tbUser = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnUpdatePass = new javax.swing.JButton();
        txtNameDisp = new javax.swing.JTextField();
        txtEmplNoDisp = new javax.swing.JTextField();
        txtPasswordUser = new javax.swing.JTextField();
        lblSuccess = new javax.swing.JLabel();
        tbReport = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtReport = new javax.swing.JTextArea();
        btnReports = new javax.swing.JButton();
        tbManageUser = new javax.swing.JPanel();
        lblUserNAme = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtUserNo = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        btnUpdateUser = new javax.swing.JButton();
        btnCreateUser = new javax.swing.JButton();
        btnRemoveUser = new javax.swing.JButton();
        lblUserRemoved = new javax.swing.JLabel();
        chkManager = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        lblRemoved = new javax.swing.JLabel();
        lblUpdate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblHello.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        lblHello.setForeground(new java.awt.Color(102, 204, 255));
        lblHello.setText("jLabel1");

        lblDateTime.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        lblDateTime.setForeground(new java.awt.Color(153, 204, 255));
        lblDateTime.setText("jLabel1");

        btnLogOut.setBackground(new java.awt.Color(225, 0, 51));
        btnLogOut.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        tbMain.setBackground(new java.awt.Color(255, 255, 255));

        tbShop.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btn0.setText("x10");
        buttonGroup1.add(btn0);
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btn4.setText("+4");
        buttonGroup1.add(btn4);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn3.setText("+3");
        buttonGroup1.add(btn3);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn2.setText("+2");
        buttonGroup1.add(btn2);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn1.setText("+1");
        buttonGroup1.add(btn1);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Quantity:");

        jButton7.setBackground(new java.awt.Color(255, 51, 51));
        jButton7.setText("Clear");
        buttonGroup1.add(jButton7);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnOrange.setBackground(new java.awt.Color(102, 204, 255));
        btnOrange.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnOrange.setForeground(new java.awt.Color(255, 255, 255));
        btnOrange.setText("Orange");
        btnOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrangeActionPerformed(evt);
            }
        });

        btnApple.setBackground(new java.awt.Color(102, 204, 255));
        btnApple.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnApple.setForeground(new java.awt.Color(255, 255, 255));
        btnApple.setText("Apple");
        btnApple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppleActionPerformed(evt);
            }
        });

        btnPotato.setBackground(new java.awt.Color(102, 204, 255));
        btnPotato.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnPotato.setForeground(new java.awt.Color(255, 255, 255));
        btnPotato.setText("Potato");
        btnPotato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPotatoActionPerformed(evt);
            }
        });

        btnCarrot.setBackground(new java.awt.Color(102, 204, 255));
        btnCarrot.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnCarrot.setForeground(new java.awt.Color(255, 255, 255));
        btnCarrot.setText("Carrot");
        btnCarrot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarrotActionPerformed(evt);
            }
        });

        btnMilk.setBackground(new java.awt.Color(102, 204, 255));
        btnMilk.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnMilk.setForeground(new java.awt.Color(255, 255, 255));
        btnMilk.setText("Milk");
        btnMilk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMilkActionPerformed(evt);
            }
        });

        btnORange3.setBackground(new java.awt.Color(102, 204, 255));
        btnORange3.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnORange3.setForeground(new java.awt.Color(255, 255, 255));
        btnORange3.setText("Banana");
        btnORange3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnORange3ActionPerformed(evt);
            }
        });

        btnOnion.setBackground(new java.awt.Color(102, 204, 255));
        btnOnion.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnOnion.setForeground(new java.awt.Color(255, 255, 255));
        btnOnion.setText("Onion");
        btnOnion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnionActionPerformed(evt);
            }
        });

        btnBread.setBackground(new java.awt.Color(102, 204, 255));
        btnBread.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnBread.setForeground(new java.awt.Color(255, 255, 255));
        btnBread.setText("Bread");
        btnBread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBreadActionPerformed(evt);
            }
        });

        btnEggs.setBackground(new java.awt.Color(102, 204, 255));
        btnEggs.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnEggs.setForeground(new java.awt.Color(255, 255, 255));
        btnEggs.setText("Eggs");
        btnEggs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEggsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnApple, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnORange3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOrange, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnPotato, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCarrot, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnMilk, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEggs, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBread, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOnion, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnApple, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOrange, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnORange3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPotato, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarrot, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOnion, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMilk, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBread, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEggs, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        lblQty.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N

        txtOrder.setColumns(20);
        txtOrder.setRows(5);
        jScrollPane3.setViewportView(txtOrder);

        jLabel2.setText("Qty");

        jLabel3.setText("Description");

        jLabel4.setText("Cost");

        jLabel13.setText("Cost");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn4)
                        .addGap(18, 18, 18)
                        .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQty, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn0, btn1, btn2, btn3, btn4, jButton7});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQty, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn0, btn1, btn2, btn3, btn4, jButton7});

        btnClear.setBackground(new java.awt.Color(255, 0, 0));
        btnClear.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear Order");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnCheckOut.setBackground(new java.awt.Color(0, 255, 102));
        btnCheckOut.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnCheckOut.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckOut.setText("Check Out");
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 255));
        jLabel5.setText("Order Total:");

        lblTotal.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N

        javax.swing.GroupLayout tbShopLayout = new javax.swing.GroupLayout(tbShop);
        tbShop.setLayout(tbShopLayout);
        tbShopLayout.setHorizontalGroup(
            tbShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbShopLayout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177)
                .addGroup(tbShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(tbShopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tbShopLayout.setVerticalGroup(
            tbShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbShopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(tbShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tbShopLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnClear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        tbMain.addTab("Shopping Main", tbShop);

        tbUser.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel7.setText("Full Name:");

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel11.setText("Employee Number:");

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel12.setText("Password:");

        btnUpdatePass.setBackground(new java.awt.Color(0, 255, 102));
        btnUpdatePass.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnUpdatePass.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdatePass.setText("Update Password");
        btnUpdatePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tbUserLayout = new javax.swing.GroupLayout(tbUser);
        tbUser.setLayout(tbUserLayout);
        tbUserLayout.setHorizontalGroup(
            tbUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbUserLayout.createSequentialGroup()
                .addGroup(tbUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tbUserLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(tbUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(tbUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnUpdatePass, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                            .addComponent(txtNameDisp)
                            .addComponent(txtEmplNoDisp)
                            .addComponent(txtPasswordUser, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)))
                    .addGroup(tbUserLayout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(lblSuccess, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(253, Short.MAX_VALUE))
        );
        tbUserLayout.setVerticalGroup(
            tbUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbUserLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(tbUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(tbUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEmplNoDisp, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(tbUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPasswordUser, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addComponent(btnUpdatePass, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(lblSuccess, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        tbMain.addTab("User Profile", tbUser);

        tbReport.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel6.setText("Report:");

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Clear Report Data");

        txtReport.setColumns(20);
        txtReport.setRows(5);
        jScrollPane2.setViewportView(txtReport);

        btnReports.setText("Display Totals");
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tbReportLayout = new javax.swing.GroupLayout(tbReport);
        tbReport.setLayout(tbReportLayout);
        tbReportLayout.setHorizontalGroup(
            tbReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbReportLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(tbReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tbReportLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnReports, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tbReportLayout.createSequentialGroup()
                        .addGroup(tbReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(tbReportLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tbReportLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 456, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(85, 85, 85))))
        );
        tbReportLayout.setVerticalGroup(
            tbReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbReportLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(tbReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(btnReports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        tbMain.addTab("Reports", tbReport);

        tbManageUser.setBackground(new java.awt.Color(255, 255, 255));

        lblUserNAme.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        lblUserNAme.setText("First Name:");

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel8.setText("Password:");

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel9.setText("User Number:");

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel10.setText("Manager");

        txtUserNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNoActionPerformed(evt);
            }
        });

        btnUpdateUser.setBackground(new java.awt.Color(102, 204, 255));
        btnUpdateUser.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnUpdateUser.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateUser.setText("Update User");
        btnUpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUserActionPerformed(evt);
            }
        });

        btnCreateUser.setBackground(new java.awt.Color(51, 255, 51));
        btnCreateUser.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnCreateUser.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateUser.setText("Create User");
        btnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUserActionPerformed(evt);
            }
        });

        btnRemoveUser.setBackground(new java.awt.Color(255, 0, 0));
        btnRemoveUser.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        btnRemoveUser.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveUser.setText("Remove User");
        btnRemoveUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveUserActionPerformed(evt);
            }
        });

        lblUserRemoved.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel19.setText("Last Name:");

        jLabel20.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel20.setText("Enter employee number and press enter to find existing user.");

        javax.swing.GroupLayout tbManageUserLayout = new javax.swing.GroupLayout(tbManageUser);
        tbManageUser.setLayout(tbManageUserLayout);
        tbManageUserLayout.setHorizontalGroup(
            tbManageUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbManageUserLayout.createSequentialGroup()
                .addGroup(tbManageUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tbManageUserLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(tbManageUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tbManageUserLayout.createSequentialGroup()
                                .addGap(209, 209, 209)
                                .addComponent(btnRemoveUser, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                                .addComponent(lblUserRemoved, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tbManageUserLayout.createSequentialGroup()
                                .addGroup(tbManageUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tbManageUserLayout.createSequentialGroup()
                                        .addGroup(tbManageUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(tbManageUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(tbManageUserLayout.createSequentialGroup()
                                                .addComponent(chkManager)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(txtLastName)
                                            .addComponent(txtPassword)))
                                    .addGroup(tbManageUserLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(tbManageUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(tbManageUserLayout.createSequentialGroup()
                                                .addGroup(tbManageUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblUserNAme, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(tbManageUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                                                    .addComponent(txtUserNo)))
                                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(383, 383, 383))
                            .addGroup(tbManageUserLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(btnUpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(btnCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(tbManageUserLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(lblRemoved, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(tbManageUserLayout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(lblUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tbManageUserLayout.setVerticalGroup(
            tbManageUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbManageUserLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tbManageUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserNo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tbManageUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserNAme, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tbManageUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(tbManageUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(tbManageUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tbManageUserLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(chkManager)))
                .addGap(18, 18, 18)
                .addComponent(lblUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tbManageUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpdateUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(tbManageUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoveUser, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserRemoved, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblRemoved, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        tbMain.addTab("Manage User", tbManageUser);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblHello, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153)
                .addComponent(lblDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbMain, javax.swing.GroupLayout.PREFERRED_SIZE, 924, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblHello, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDateTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tbMain)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //displaying name
        lblHello.setText("Hello, " + loggedInEmployee.getFirstName());
        
        //displaying date and time
        Date dateAndTime = Calendar.getInstance().getTime();    
        lblDateTime.setText(dateAndTime.toString());
        
        //setting default quantity
        lblQty.setText(Integer.toString(qtySelect));
        
        
        //setting default order total
        lblTotal.setText(String.format("%.2f", orderTotal));
        
        //setting user profile
        txtNameDisp.setText(loggedInEmployee.getFirstName());
        txtEmplNoDisp.setText(Integer.toString(loggedInEmployee.getEmployeeNo()));
        txtPasswordUser.setText(loggedInEmployee.getPassword());
        
        
    }//GEN-LAST:event_formWindowOpened

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // button takes back to log in screen
        UserLogin logOut = new UserLogin(employees);         
        this.dispose();
        logOut.setVisible(true);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnRemoveUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveUserActionPerformed
        int userNo = Integer.parseInt(txtUserNo.getText());

        for (Employee employee : employees)
        {
            if (employee.getEmployeeNo() == userNo)
            {
                employees.remove(employee);
            }
        }

        lblRemoved.setText("User removed");

    }//GEN-LAST:event_btnRemoveUserActionPerformed

    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
        //reading variables for new employee
        int userNoIn = Integer.parseInt(txtUserNo.getText());
        String firstNameIn = txtFirstName.getText();
        String lastNameIn = txtLastName.getText();
        String passwordIn = txtPassword.getText();
        boolean managerIn = false;

        //checking if employee is manager
        if(chkManager.isSelected())
        {
            managerIn = true;
        }
        else
        {
            managerIn = false;
        }

        //creating new employee
        Employee employeeNew = new Employee(userNoIn, firstNameIn, lastNameIn, passwordIn, managerIn);

        //adding to arraylist
        employees.add(employeeNew);

        lblUpdate.setText("User created");
        

    }//GEN-LAST:event_btnCreateUserActionPerformed

    private void btnUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUserActionPerformed
        int userNo = Integer.parseInt(txtUserNo.getText());
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        String password = txtPassword.getText();
        boolean manager = chkManager.isSelected();

        for (Employee employee : employees)
        {
            if (userNo == employee.getEmployeeNo())
            {
                employee.setFirstName(firstName);
                employee.setLastName(lastName);
                employee.setPassword(password);
                employee.setManager(manager);
            }
        }

        lblUpdate.setText("User updated");

    }//GEN-LAST:event_btnUpdateUserActionPerformed

    private void txtUserNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNoActionPerformed
        int userNo = Integer.parseInt(txtUserNo.getText());

        for (Employee employee : employees)
        {
            if (userNo == employee.getEmployeeNo())
            {
                txtFirstName.setText(employee.getFirstName());
                txtLastName.setText(employee.getLastName());
                txtPassword.setText(employee.getPassword());
                if (employee.getManager() == true){
                    chkManager.setSelected(true);
                }
                else
                {
                    chkManager.setSelected(false);
                }
            }
        }
    }//GEN-LAST:event_txtUserNoActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed

        
        for (Order order : orders)
        {
            txtReport.append(order.getEmployeeNo() + ", " + order.getTotal() + ", " + order.getCount());
        }
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnUpdatePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePassActionPerformed
        String newPass = txtPasswordUser.getText();

        for (Employee employee : employees)
        {
            if (employee.getEmployeeNo() == loggedInEmployee.getEmployeeNo())
            {
                employee.setPassword(newPass);
            }
        }

        lblSuccess.setText("Password updated!");
    }//GEN-LAST:event_btnUpdatePassActionPerformed

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed

        int emplNo = loggedInEmployee.getEmployeeNo();
        double orderComplete = Double.parseDouble(lblTotal.getText());
        
        Order orderComplete = new Order(emplNo, orderComplete);
        orders.add(orderComplete);


        //resetting running total
        orderTotal = 0.0;

        //resetting order list
        txtOrder.setText(null);
        //clearing running total
        lblTotal.setText(String.format("%.2f",orderTotal));

    }//GEN-LAST:event_btnCheckOutActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        //reseting running total
        orderTotal = 0.0;

        //clearing order list
        txtOrder.setText(null);
        //clearing running total
        lblTotal.setText(String.format("%.2f",orderTotal));

    }//GEN-LAST:event_btnClearActionPerformed

    private void btnEggsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEggsActionPerformed
        //getting current quantity
        int qty = Integer.parseInt(lblQty.getText());
        //setting eggs string
        String eggs = "Eggs";
        //setting cost variable
        double cost = 1.50;
        //calculating total
        double total = cost * qty;

        //appending to order list
        txtOrder.append(qty + " X\t" + eggs + "\t\t" + String.format("%.2f",cost) + "\t" + String.format("%.2f",total) + "\n");
        lblQty.setText("1");

        //updating running total
        orderTotal += total;
        lblTotal.setText(String.format("%.2f",orderTotal));
    }//GEN-LAST:event_btnEggsActionPerformed

    private void btnBreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBreadActionPerformed
        //getting current quantity
        int qty = Integer.parseInt(lblQty.getText());
        //setting bread string
        String bread = "Bread";
        //setting cost
        double cost = 0.80;
        //calculating total
        double total = cost * qty;

        //appending to order list
        txtOrder.append(qty + " X\t" + bread + "\t\t" + String.format("%.2f",cost) + "\t" + String.format("%.2f",total) + "\n");
        lblQty.setText("1");

        //updating running total
        orderTotal += total;
        lblTotal.setText(String.format("%.2f",orderTotal));
    }//GEN-LAST:event_btnBreadActionPerformed

    private void btnOnionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnionActionPerformed

        //getting current quantity
        int qty = Integer.parseInt(lblQty.getText());
        //setting onion variable
        String onion = "Onion";
        //setting cost
        double cost = 0.30;
        //calculating total
        double total = cost * qty;

        //appending to order list
        txtOrder.append(qty + " X\t" + onion + "\t\t" + String.format("%.2f",cost) + "\t" + String.format("%.2f",total) + "\n");
        lblQty.setText("1");

        //updating runing total
        orderTotal += total;
        lblTotal.setText(String.format("%.2f",orderTotal));
    }//GEN-LAST:event_btnOnionActionPerformed

    private void btnORange3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnORange3ActionPerformed
        //getting current quantity
        int qty = Integer.parseInt(lblQty.getText());
        //setting Banana variable
        String bananas = "Banana";
        //setting cost
        double cost = 0.25;
        //setting total
        double total = cost * qty;

        //printing to order list
        txtOrder.append(qty + " X\t" + bananas + "\t\t" + String.format("%.2f",cost) + "\t" + String.format("%.2f",total) + "\n");
        lblQty.setText("1");

        //updating running total
        orderTotal += total;
        lblTotal.setText(String.format("%.2f",orderTotal));

    }//GEN-LAST:event_btnORange3ActionPerformed

    private void btnMilkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMilkActionPerformed
        //getting current quantity
        int qty = Integer.parseInt(lblQty.getText());
        //setting milk vairable
        String milk = "Milk";
        //setting cost
        double cost = 1.25;
        //calculating total
        double total = cost * qty;

        //appending to order list
        txtOrder.append(qty + " X\t" + milk + "\t\t" + String.format("%.2f",cost) + "\t" + String.format("%.2f",total) + "\n");
        lblQty.setText("1");

        //updating running total
        orderTotal += total;
        lblTotal.setText(String.format("%.2f",orderTotal));
    }//GEN-LAST:event_btnMilkActionPerformed

    private void btnCarrotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarrotActionPerformed
        //getting current quantity
        int qty = Integer.parseInt(lblQty.getText());
        //setting carrots variable
        String carrots = "Carrot";
        //setting cost
        double cost = 0.15;
        //calculating cost
        double total = cost * qty;

        //[ronting to order list
        txtOrder.append(qty + " X\t" + carrots + "\t\t" + String.format("%.2f",cost) + "\t" + String.format("%.2f",total) + "\n");
        lblQty.setText("1");

        //updating running total
        orderTotal += total;
        lblTotal.setText(String.format("%.2f",orderTotal));
    }//GEN-LAST:event_btnCarrotActionPerformed

    private void btnPotatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPotatoActionPerformed

        //getting current quantity
        int qty = Integer.parseInt(lblQty.getText());
        //setting potatoes string
        String potatoes = "potatoes";
        //setting cost variable
        double cost = 0.35;
        //calculating total
        double total = cost * qty;

        //printing to order list
        txtOrder.append(qty + " X\t" + potatoes + "\t\t" + String.format("%.2f",cost) + "\t" + String.format("%.2f",total) + "\n");
        lblQty.setText("1");

        //updating running total
        orderTotal += total;
        lblTotal.setText(String.format("%.2f",orderTotal));
    }//GEN-LAST:event_btnPotatoActionPerformed

    private void btnAppleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppleActionPerformed
        //getting current quantity
        int qty = Integer.parseInt(lblQty.getText());
        //setting Apples variable
        String apples = "Apples";
        //setting cost
        double cost = 0.30;
        //setting total
        double total = cost*qty;

        //printing to order list
        txtOrder.append(qty + " X\t" + apples + "\t\t" + String.format("%.2f",cost) + "\t" + String.format("%.2f",total) + "\n");
        lblQty.setText("1");

        //updating running total
        orderTotal += total;
        lblTotal.setText(String.format("%.2f",orderTotal));

    }//GEN-LAST:event_btnAppleActionPerformed

    private void btnOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrangeActionPerformed
        //getting current quantity
        int qty = Integer.parseInt(lblQty.getText());
        //setting orange variable
        String orange = "Orange";
        //setting cost
        double cost = 0.70;
        //setting total
        double total = cost * qty;

        //printing to order list
        txtOrder.append(qty + " X\t" + orange + "\t\t" + String.format("%.2f",cost) + "\t" + String.format("%.2f",total) + "\n");
        lblQty.setText("1");

        //updating running total
        orderTotal += total;
        lblTotal.setText(String.format("%.2f",orderTotal));
    }//GEN-LAST:event_btnOrangeActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        //clear button variable to reset to default
        int newQty = 1;

        //setting quantty to default
        lblQty.setText(Integer.toString(newQty));
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        //setting button variable
        int btn1 = 1;
        //reading current quantity
        int qtySelect = Integer.parseInt(lblQty.getText());
        //adding button and current quantity
        int newQty = btn1 + qtySelect;

        //setting new quantity
        lblQty.setText(Integer.toString(newQty));
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        //setting button variable
        int btn2 = 2;
        //reading current quantity
        int qtySelect = Integer.parseInt(lblQty.getText());
        //adding button and current quantity
        int newQty = btn2 + qtySelect;

        //setting new quantity

        lblQty.setText(Integer.toString(newQty));
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        //setting button variable
        int btn3 = 3;
        //reading current quantity
        int qtySelect = Integer.parseInt(lblQty.getText());
        //adding button and current quantity
        int newQty = btn3 + qtySelect;

        //setting new quantity
        lblQty.setText(Integer.toString(newQty));

    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        //setting button variable
        int btn4 = 4;
        //reading current quantity
        int qtySelect = Integer.parseInt(lblQty.getText());
        //adding button and current quantity
        int newQty = btn4 + qtySelect;

        //setting new quantity
        lblQty.setText(Integer.toString(newQty));
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        //setting button variable
        int btn10 = 10;
        //reading current quantity
        int qtySelect = Integer.parseInt(lblQty.getText());
        //multiplying button and current quantity
        int newQty = btn10 * qtySelect;

        //setting new quantity
        lblQty.setText(Integer.toString(newQty));
    }//GEN-LAST:event_btn0ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EposMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EposMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EposMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EposMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new EposMainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btnApple;
    private javax.swing.JButton btnBread;
    private javax.swing.JButton btnCarrot;
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JButton btnEggs;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnMilk;
    private javax.swing.JButton btnORange3;
    private javax.swing.JButton btnOnion;
    private javax.swing.JButton btnOrange;
    private javax.swing.JButton btnPotato;
    private javax.swing.JButton btnRemoveUser;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnUpdatePass;
    private javax.swing.JButton btnUpdateUser;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JCheckBox chkManager;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDateTime;
    private javax.swing.JLabel lblHello;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblRemoved;
    private javax.swing.JLabel lblSuccess;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblUpdate;
    private javax.swing.JLabel lblUserNAme;
    private javax.swing.JLabel lblUserRemoved;
    private javax.swing.JTabbedPane tbMain;
    private javax.swing.JPanel tbManageUser;
    private javax.swing.JPanel tbReport;
    private javax.swing.JPanel tbShop;
    private javax.swing.JPanel tbUser;
    private javax.swing.JTextField txtEmplNoDisp;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtNameDisp;
    private javax.swing.JTextArea txtOrder;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPasswordUser;
    private javax.swing.JTextArea txtReport;
    private javax.swing.JTextField txtUserNo;
    // End of variables declaration//GEN-END:variables
}
